#!/bin/sh

ufw default deny incoming
ufw default allow outgoing

ufw allow 22/tcp
ufw allow 2222/tcp
ufw allow 80/tcp

ufw enable

apt-get install git
mkdir /opt/src
cd /opt/src

git clone https://github.com/samgiles/remote-development-env
cd remote-development-env

cp ~root/.ssh/authorized_keys ./ssh/id_rsa.pub

echo "Building dev-server image"
docker build -t dev-server .
docker run -d --init --privileged --tty -p 0.0.0.0:2222:22 -p 0.0.0.0:80:80 -t dev-server
